Update scan-for-secrets.yml

diff --git a/workflow-templates/scan-for-secrets.yml b/workflow-templates/scan-for-secrets.yml
--- a/workflow-templates/scan-for-secrets.yml
+++ b/workflow-templates/scan-for-secrets.yml
@@ -1,35 +1,38 @@
-
 name: Scan for Secrets
 
 on:
-  push:
-    branches: [ $default-branch ]
-  pull_request:
+ push:
+   branches: [ $default-branch ]
+ pull_request:
 
+
+# GitHub Action workflow has permissions to write comments and update pull requests
 permissions:
-  contents: read
-  id-token: write
-  issues: write
-  pull-requests: write
+ contents: read
+ id-token: write
+ issues: write
+ pull-requests: write
 
 jobs:
-  TruffleHog:
-    runs-on: self-hosted
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+ TruffleHog:
+   runs-on: self-hosted
+   defaults:
+     run:
+       shell: bash
+   steps:
+     - name: Checkout code
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
 
-      - name: TruffleHog OSS
-        id: trufflehog
-        uses: trufflesecurity/trufflehog@main
-        with:
-          extra_args: --debug --only-verified
+     - name: TruffleHog OSS
+       id: trufflehog
+       uses: trufflesecurity/trufflehog@main
+       continue-on-error: true
+       with:
+         extra_args: --debug --only-verified
 
-      - name: Scan Results Status
-        if: steps.trufflehog.outcome == 'failure'
-        run: exit 1
+# Finally, this will make sure that if a secret is detected, the run fails:
+     - name: Scan Results Status
+       if: steps.trufflehog.outcome == 'failure'
+       run: exit 1
